name: Run Serenity Tests

on:
  push:
    branches:
      - main  # Change this to your target branch
  pull_request:
    branches:
      - main

jobs:
  serenity-tests:
    runs-on: ubuntu-latest  # or 'windows-latest' if running on Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use the required JDK distribution
          java-version: '17'       # Adjust based on your project requirements

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Run Serenity Tests
        run: mvn clean verify -Dserenity.project.name="GitHub Actions Run"

      - name: Upload Serenity Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: target/site/serenity
